- hosts: all 
  tasks:
    - name: remove old wazub
      command: sudo yum remove wazuh-agent -y  
    - name: install new wazuh
      command: sudo WAZUH_MANAGER='elk.wazuh.local' yum install https://packages.wazuh.com/3.x/yum/wazuh-agent-3.12.2-1.x86_64.rpm -y
    
